# Generated by Django 4.0.5 on 2022-06-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_employeeexperience_employeeeducation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeeducation',
            name='coursessc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
